Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'config/initializers/**/*.rb'

Style/WordArray:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'

Style/MixinUsage:
  Exclude:
    - 'config/routes.rb'
    - 'config/main_routes.rb'

Metrics/LineLength:
  Max: 140

Style/FrozenStringLiteralComment:
  Enabled: false
